/**
 * Mock data and functions for development/demo when backend is unavailable
 */

export interface MockHistoryItem {
  id: string
  prompt: string
  response: string
  model: string
  timestamp: string
  temperature?: number
}

const mockHistory: MockHistoryItem[] = [
  {
    id: '1',
    prompt: 'Explain quantum computing in simple terms',
    response: 'Quantum computing uses quantum mechanical phenomena like superposition and entanglement to perform computations. Unlike classical bits that are either 0 or 1, quantum bits (qubits) can exist in multiple states simultaneously, allowing quantum computers to solve certain problems exponentially faster than classical computers.',
    model: 'gpt-4o-mini',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    temperature: 0.7,
  },
  {
    id: '2',
    prompt: 'What are the best practices for React performance?',
    response: 'Key React performance practices include: 1) Use React.memo for expensive components, 2) Implement useMemo and useCallback to prevent unnecessary recalculations, 3) Code splitting with React.lazy and Suspense, 4) Virtualize long lists, 5) Optimize images and assets, 6) Avoid inline object/function creation in render, 7) Use production builds, and 8) Profile with React DevTools.',
    model: 'gpt-4o-mini',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    temperature: 0.7,
  },
  {
    id: '3',
    prompt: 'How does async/await work in JavaScript?',
    response: 'Async/await is syntactic sugar built on Promises. The `async` keyword makes a function return a Promise, and `await` pauses execution until the Promise resolves. It makes asynchronous code look synchronous and easier to read. Under the hood, it uses generators and the event loop to handle the asynchronous flow.',
    model: 'gpt-4o-mini',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    temperature: 0.7,
  },
]

export function getMockHistory(query?: string): MockHistoryItem[] {
  if (!query) return mockHistory
  const lowerQuery = query.toLowerCase()
  return mockHistory.filter(
    (item) =>
      item.prompt.toLowerCase().includes(lowerQuery) ||
      item.response.toLowerCase().includes(lowerQuery)
  )
}

export function getMockHistoryItem(id: string): MockHistoryItem | null {
  return mockHistory.find((item) => item.id === id) || null
}

export async function mockGenerateResponse(
  prompt: string,
  model: string,
  temperature: number
): Promise<string> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1500 + Math.random() * 1000))
  
  // Simple mock responses based on prompt keywords
  const lowerPrompt = prompt.toLowerCase()
  
  if (lowerPrompt.includes('hello') || lowerPrompt.includes('hi')) {
    return 'Hello! How can I assist you today?'
  }
  
  if (lowerPrompt.includes('explain') || lowerPrompt.includes('what is')) {
    return `Based on your question about "${prompt.slice(0, 50)}...", here's a comprehensive explanation:\n\nThis is a detailed response that would normally come from an AI model. The response is tailored to your query and provides useful information. In a real implementation, this would be generated by the AI model you've selected (${model}) with the temperature setting of ${temperature}.`
  }
  
  if (lowerPrompt.includes('code') || lowerPrompt.includes('programming')) {
    return `Here's a code example related to your question:\n\n\`\`\`javascript\nfunction example() {\n  // Your code here\n  return "result";\n}\n\`\`\`\n\nThis demonstrates the concept you asked about.`
  }
  
  // Default response
  return `Thank you for your question: "${prompt}"\n\nThis is a mock AI response. In production, this would be generated by ${model} with temperature ${temperature}. The response would be contextually relevant and helpful based on your prompt.`
}
